/*
 * Licensed to the Association pour la cooperation numerique (ACN) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ACN licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type { FormApp, User, Entity, Event, FormDefinition, ConflictDetail } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "admin",
    createdAt: new Date("2024-01-15"),
    lastLogin: new Date("2025-01-09"),
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@company.com",
    role: "manager",
    createdAt: new Date("2024-02-20"),
    lastLogin: new Date("2025-01-08"),
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    role: "viewer",
    createdAt: new Date("2024-03-10"),
    lastLogin: new Date("2025-01-07"),
  },
]

export const mockFormApps: FormApp[] = [
  {
    id: "fa-001",
    name: "Field Survey 2025",
    description: "Annual field data collection for environmental monitoring",
    version: "2.1.0",
    formsCount: 12,
    entitiesBackendSynced: 2847,
    entitiesExternalSynced: 2820,
    totalEntities: 2850,
    deploymentUrl: "https://forms.company.com/field-survey-2025",
    qrCodeData: "https://forms.company.com/field-survey-2025",
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2025-01-09"),
    createdBy: "Sarah Johnson",
    status: {
      status: "active",
      lastSyncedAt: new Date("2025-01-09T14:30:00"),
      syncHealth: "healthy",
    },
    externalIntegration: "OpenFn",
    versionHistory: [
      {
        id: "vh-001",
        version: "1.0.0",
        timestamp: new Date("2024-11-01T09:00:00"),
        changedBy: "Sarah Johnson",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Field Survey 2025" },
          { field: "description", newValue: "Annual field data collection for environmental monitoring" },
          { field: "formsCount", newValue: 8 },
        ],
        description: "Initial version created",
      },
      {
        id: "vh-002",
        version: "2.0.0",
        timestamp: new Date("2024-12-15T14:30:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          { field: "formsCount", oldValue: 8, newValue: 12 },
          { field: "externalIntegration", oldValue: null, newValue: "OpenFn" },
        ],
        description: "Added 4 new forms and integrated with OpenFn",
      },
      {
        id: "vh-003",
        version: "2.1.0",
        timestamp: new Date("2025-01-05T10:15:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          {
            field: "description",
            oldValue: "Annual field data collection for environmental monitoring",
            newValue: "Annual field data collection for environmental monitoring - Updated validation rules",
          },
        ],
        description: "Updated validation rules for water quality tests",
      },
    ],
  },
  {
    id: "fa-002",
    name: "Customer Feedback",
    description: "In-store customer satisfaction surveys",
    version: "1.5.2",
    formsCount: 5,
    entitiesBackendSynced: 1523,
    entitiesExternalSynced: 1498,
    totalEntities: 1530,
    deploymentUrl: "https://forms.company.com/customer-feedback",
    qrCodeData: "https://forms.company.com/customer-feedback",
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2025-01-09"),
    createdBy: "Michael Chen",
    status: {
      status: "active",
      lastSyncedAt: new Date("2025-01-09T13:15:00"),
      syncHealth: "warning",
    },
    externalIntegration: "OpenSPP",
    versionHistory: [
      {
        id: "vh-004",
        version: "1.0.0",
        timestamp: new Date("2024-08-15T08:00:00"),
        changedBy: "Michael Chen",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Customer Feedback" },
          { field: "formsCount", newValue: 3 },
        ],
        description: "Initial version created",
      },
      {
        id: "vh-005",
        version: "1.5.0",
        timestamp: new Date("2024-10-20T11:45:00"),
        changedBy: "Michael Chen",
        changeType: "updated",
        changes: [
          { field: "formsCount", oldValue: 3, newValue: 5 },
          { field: "externalIntegration", oldValue: null, newValue: "OpenSPP" },
        ],
        description: "Added service rating form and OpenSPP integration",
      },
      {
        id: "vh-006",
        version: "1.5.2",
        timestamp: new Date("2025-01-02T15:20:00"),
        changedBy: "Michael Chen",
        changeType: "updated",
        changes: [
          {
            field: "description",
            oldValue: "In-store customer satisfaction surveys",
            newValue: "In-store customer satisfaction surveys - Enhanced feedback collection",
          },
        ],
        description: "Minor bug fixes and UI improvements",
      },
    ],
  },
  {
    id: "fa-003",
    name: "Equipment Inspection",
    description: "Daily equipment safety and maintenance checks",
    version: "3.0.1",
    formsCount: 8,
    entitiesBackendSynced: 4521,
    entitiesExternalSynced: 4521,
    totalEntities: 4521,
    deploymentUrl: "https://forms.company.com/equipment-inspection",
    qrCodeData: "https://forms.company.com/equipment-inspection",
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2025-01-09"),
    createdBy: "Sarah Johnson",
    status: {
      status: "active",
      lastSyncedAt: new Date("2025-01-09T15:00:00"),
      syncHealth: "healthy",
    },
    externalIntegration: "Generic Mock",
    versionHistory: [
      {
        id: "vh-007",
        version: "1.0.0",
        timestamp: new Date("2024-05-20T09:00:00"),
        changedBy: "Sarah Johnson",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Equipment Inspection" },
          { field: "formsCount", newValue: 4 },
        ],
        description: "Initial version created",
      },
      {
        id: "vh-008",
        version: "2.0.0",
        timestamp: new Date("2024-08-10T13:30:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [{ field: "formsCount", oldValue: 4, newValue: 6 }],
        description: "Added maintenance log and safety checklist forms",
      },
      {
        id: "vh-009",
        version: "3.0.0",
        timestamp: new Date("2024-11-15T10:00:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          { field: "formsCount", oldValue: 6, newValue: 8 },
          { field: "externalIntegration", oldValue: null, newValue: "Generic Mock" },
        ],
        description: "Major update with new inspection forms and mock integration",
      },
      {
        id: "vh-010",
        version: "3.0.1",
        timestamp: new Date("2025-01-08T14:45:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          {
            field: "description",
            oldValue: "Daily equipment safety and maintenance checks",
            newValue: "Daily equipment safety and maintenance checks - Improved reporting",
          },
        ],
        description: "Patch: Fixed reporting issues",
      },
    ],
  },
  {
    id: "fa-004",
    name: "Inventory Audit Q1",
    description: "Quarterly inventory verification and reconciliation",
    version: "1.0.0",
    formsCount: 3,
    entitiesBackendSynced: 0,
    entitiesExternalSynced: 0,
    totalEntities: 0,
    deploymentUrl: "https://forms.company.com/inventory-audit-q1",
    qrCodeData: "https://forms.company.com/inventory-audit-q1",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-08"),
    createdBy: "Michael Chen",
    status: {
      status: "draft",
      lastSyncedAt: null,
      syncHealth: "healthy",
    },
    externalIntegration: null,
    versionHistory: [
      {
        id: "vh-011",
        version: "1.0.0",
        timestamp: new Date("2025-01-05T10:00:00"),
        changedBy: "Michael Chen",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Inventory Audit Q1" },
          { field: "formsCount", newValue: 3 },
        ],
        description: "Initial version created",
      },
    ],
  },
  {
    id: "fa-005",
    name: "Health & Safety Compliance",
    description: "Workplace safety compliance and incident reporting",
    version: "2.3.5",
    formsCount: 15,
    entitiesBackendSynced: 892,
    entitiesExternalSynced: 845,
    totalEntities: 920,
    deploymentUrl: "https://forms.company.com/health-safety",
    qrCodeData: "https://forms.company.com/health-safety",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2025-01-09"),
    createdBy: "Sarah Johnson",
    status: {
      status: "active",
      lastSyncedAt: new Date("2025-01-09T12:45:00"),
      syncHealth: "error",
    },
    externalIntegration: "OpenSPP",
    versionHistory: [
      {
        id: "vh-012",
        version: "1.0.0",
        timestamp: new Date("2024-03-10T08:00:00"),
        changedBy: "Sarah Johnson",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Health & Safety Compliance" },
          { field: "formsCount", newValue: 8 },
        ],
        description: "Initial version created",
      },
      {
        id: "vh-013",
        version: "2.0.0",
        timestamp: new Date("2024-06-15T09:30:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [{ field: "formsCount", oldValue: 8, newValue: 12 }],
        description: "Added incident reporting and near-miss forms",
      },
      {
        id: "vh-014",
        version: "2.3.0",
        timestamp: new Date("2024-10-01T11:00:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          { field: "formsCount", oldValue: 12, newValue: 15 },
          { field: "externalIntegration", oldValue: null, newValue: "OpenSPP" },
        ],
        description: "Added training and compliance tracking forms with OpenSPP integration",
      },
      {
        id: "vh-015",
        version: "2.3.5",
        timestamp: new Date("2025-01-06T14:20:00"),
        changedBy: "Sarah Johnson",
        changeType: "updated",
        changes: [
          {
            field: "description",
            oldValue: "Workplace safety compliance and incident reporting",
            newValue: "Workplace safety compliance and incident reporting - Enhanced tracking",
          },
        ],
        description: "Bug fixes and performance improvements",
      },
    ],
  },
  {
    id: "fa-006",
    name: "Training Assessment",
    description: "Employee training completion and assessment forms",
    version: "1.2.0",
    formsCount: 6,
    entitiesBackendSynced: 3241,
    entitiesExternalSynced: 3241,
    totalEntities: 3241,
    deploymentUrl: "https://forms.company.com/training-assessment",
    qrCodeData: "https://forms.company.com/training-assessment",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-01-08"),
    createdBy: "Emily Rodriguez",
    status: {
      status: "active",
      lastSyncedAt: new Date("2025-01-08T16:20:00"),
      syncHealth: "healthy",
    },
    externalIntegration: "OpenFn",
    versionHistory: [
      {
        id: "vh-016",
        version: "1.0.0",
        timestamp: new Date("2024-06-01T08:00:00"),
        changedBy: "Emily Rodriguez",
        changeType: "created",
        changes: [
          { field: "name", newValue: "Training Assessment" },
          { field: "formsCount", newValue: 4 },
        ],
        description: "Initial version created",
      },
      {
        id: "vh-017",
        version: "1.1.0",
        timestamp: new Date("2024-09-10T10:30:00"),
        changedBy: "Emily Rodriguez",
        changeType: "updated",
        changes: [{ field: "formsCount", oldValue: 4, newValue: 6 }],
        description: "Added advanced assessment forms",
      },
      {
        id: "vh-018",
        version: "1.2.0",
        timestamp: new Date("2025-01-02T13:15:00"),
        changedBy: "Emily Rodriguez",
        changeType: "updated",
        changes: [{ field: "externalIntegration", oldValue: null, newValue: "OpenFn" }],
        description: "Integrated with OpenFn for automated reporting",
      },
    ],
  },
]

export const mockFormDefinitions: Record<string, FormDefinition[]> = {
  "fa-001": [
    { id: "form-001", name: "Site Assessment", version: "2.1.0", fields: 15, entityCount: 847 },
    { id: "form-002", name: "Water Quality Test", version: "2.1.0", fields: 22, entityCount: 623 },
    { id: "form-003", name: "Wildlife Observation", version: "2.0.5", fields: 18, entityCount: 1377 },
  ],
  "fa-002": [
    { id: "form-004", name: "Product Satisfaction", version: "1.5.2", fields: 12, entityCount: 892 },
    { id: "form-005", name: "Service Rating", version: "1.5.2", fields: 8, entityCount: 638 },
  ],
  "fa-003": [
    { id: "form-006", name: "Daily Safety Check", version: "3.0.1", fields: 25, entityCount: 2341 },
    { id: "form-007", name: "Maintenance Log", version: "3.0.1", fields: 19, entityCount: 2180 },
  ],
}

export const mockEntities: Record<string, Entity[]> = {
  "fa-001": [
    {
      id: "ent-001",
      formAppId: "fa-001",
      formId: "form-001",
      formName: "Site Assessment",
      createdAt: new Date("2025-01-08T09:15:00"),
      updatedAt: new Date("2025-01-09T14:22:00"),
      version: 3,
      status: "synced",
      backendSynced: true,
      externalSynced: true,
      lastSyncedAt: new Date("2025-01-09T14:30:00"),
      conflictCount: 0,
      eventCount: 8,
      data: { site_id: "SITE-2847", location: "North Ridge", status: "completed" },
    },
    {
      id: "ent-002",
      formAppId: "fa-001",
      formId: "form-002",
      formName: "Water Quality Test",
      createdAt: new Date("2025-01-08T10:30:00"),
      updatedAt: new Date("2025-01-09T11:45:00"),
      version: 2,
      status: "conflict",
      backendSynced: true,
      externalSynced: false,
      lastSyncedAt: new Date("2025-01-09T11:50:00"),
      conflictCount: 1,
      eventCount: 6,
      data: { test_id: "WQ-1523", ph_level: 7.2, turbidity: "low" },
    },
    {
      id: "ent-003",
      formAppId: "fa-001",
      formId: "form-003",
      formName: "Wildlife Observation",
      createdAt: new Date("2025-01-09T08:00:00"),
      updatedAt: new Date("2025-01-09T08:00:00"),
      version: 1,
      status: "pending",
      backendSynced: false,
      externalSynced: false,
      lastSyncedAt: null,
      conflictCount: 0,
      eventCount: 1,
      data: { observation_id: "WO-4521", species: "Red-tailed Hawk", count: 2 },
    },
    {
      id: "ent-004",
      formAppId: "fa-001",
      formId: "form-001",
      formName: "Site Assessment",
      createdAt: new Date("2025-01-07T14:20:00"),
      updatedAt: new Date("2025-01-09T09:10:00"),
      version: 5,
      status: "synced",
      backendSynced: true,
      externalSynced: true,
      lastSyncedAt: new Date("2025-01-09T09:15:00"),
      conflictCount: 2,
      eventCount: 15,
      data: { site_id: "SITE-2846", location: "East Valley", status: "in_progress" },
    },
    {
      id: "ent-005",
      formAppId: "fa-001",
      formId: "form-002",
      formName: "Water Quality Test",
      createdAt: new Date("2025-01-09T13:00:00"),
      updatedAt: new Date("2025-01-09T13:30:00"),
      version: 1,
      status: "failed",
      backendSynced: false,
      externalSynced: false,
      lastSyncedAt: new Date("2025-01-09T13:35:00"),
      conflictCount: 0,
      eventCount: 3,
      data: { test_id: "WQ-1524", ph_level: 6.8, turbidity: "medium" },
    },
  ],
}

export const mockEvents: Record<string, Event[]> = {
  "ent-001": [
    {
      id: "evt-001",
      entityId: "ent-001",
      type: "entity_created",
      timestamp: new Date("2025-01-08T09:15:00"),
      userId: "user-mobile-001",
      userName: "Field Worker A",
      deviceId: "device-android-001",
      data: { site_id: "SITE-2847", location: "North Ridge" },
      metadata: { version: 1 },
    },
    {
      id: "evt-002",
      entityId: "ent-001",
      type: "entity_updated",
      timestamp: new Date("2025-01-08T11:30:00"),
      userId: "user-mobile-001",
      userName: "Field Worker A",
      deviceId: "device-android-001",
      data: { status: "in_progress" },
      metadata: { version: 2, previousVersion: 1 },
    },
    {
      id: "evt-003",
      entityId: "ent-001",
      type: "sync_started",
      timestamp: new Date("2025-01-08T15:00:00"),
      userId: "system",
      userName: "System",
      deviceId: "device-android-001",
      data: {},
      metadata: { version: 2 },
    },
    {
      id: "evt-004",
      entityId: "ent-001",
      type: "sync_completed",
      timestamp: new Date("2025-01-08T15:00:12"),
      userId: "system",
      userName: "System",
      deviceId: "backend-server",
      data: {},
      metadata: { version: 2, syncDuration: 12000 },
    },
    {
      id: "evt-005",
      entityId: "ent-001",
      type: "entity_updated",
      timestamp: new Date("2025-01-09T14:22:00"),
      userId: "user-mobile-001",
      userName: "Field Worker A",
      deviceId: "device-android-001",
      data: { status: "completed" },
      metadata: { version: 3, previousVersion: 2 },
    },
    {
      id: "evt-006",
      entityId: "ent-001",
      type: "sync_started",
      timestamp: new Date("2025-01-09T14:25:00"),
      userId: "system",
      userName: "System",
      deviceId: "device-android-001",
      data: {},
      metadata: { version: 3 },
    },
    {
      id: "evt-007",
      entityId: "ent-001",
      type: "sync_completed",
      timestamp: new Date("2025-01-09T14:25:08"),
      userId: "system",
      userName: "System",
      deviceId: "backend-server",
      data: {},
      metadata: { version: 3, syncDuration: 8000 },
    },
    {
      id: "evt-008",
      entityId: "ent-001",
      type: "external_sync_completed",
      timestamp: new Date("2025-01-09T14:30:00"),
      userId: "system",
      userName: "System",
      deviceId: "integration-openfn",
      data: { integration: "OpenFn", externalId: "openfn-2847" },
      metadata: { version: 3, syncDuration: 5000 },
    },
  ],
  "ent-002": [
    {
      id: "evt-009",
      entityId: "ent-002",
      type: "entity_created",
      timestamp: new Date("2025-01-08T10:30:00"),
      userId: "user-mobile-002",
      userName: "Field Worker B",
      deviceId: "device-ios-001",
      data: { test_id: "WQ-1523", ph_level: 7.2 },
      metadata: { version: 1 },
    },
    {
      id: "evt-010",
      entityId: "ent-002",
      type: "sync_completed",
      timestamp: new Date("2025-01-08T16:00:00"),
      userId: "system",
      userName: "System",
      deviceId: "backend-server",
      data: {},
      metadata: { version: 1, syncDuration: 9000 },
    },
    {
      id: "evt-011",
      entityId: "ent-002",
      type: "entity_updated",
      timestamp: new Date("2025-01-09T11:45:00"),
      userId: "user-mobile-002",
      userName: "Field Worker B",
      deviceId: "device-ios-001",
      data: { turbidity: "low" },
      metadata: { version: 2, previousVersion: 1 },
    },
    {
      id: "evt-012",
      entityId: "ent-002",
      type: "conflict_detected",
      timestamp: new Date("2025-01-09T11:50:00"),
      userId: "system",
      userName: "System",
      deviceId: "backend-server",
      data: { conflictField: "turbidity", localValue: "low", remoteValue: "medium" },
      metadata: { version: 2, previousVersion: 1 },
    },
    {
      id: "evt-013",
      entityId: "ent-002",
      type: "conflict_resolved",
      timestamp: new Date("2025-01-09T11:50:05"),
      userId: "system",
      userName: "System",
      deviceId: "backend-server",
      data: { resolution: "latest_wins", finalValue: "low" },
      metadata: { version: 2, conflictResolution: "latest_wins" },
    },
    {
      id: "evt-014",
      entityId: "ent-002",
      type: "external_sync_failed",
      timestamp: new Date("2025-01-09T11:55:00"),
      userId: "system",
      userName: "System",
      deviceId: "integration-openspp",
      data: { integration: "OpenSPP", error: "Connection timeout" },
      metadata: { version: 2, errorMessage: "Connection timeout after 30s" },
    },
  ],
  "ent-003": [
    {
      id: "evt-015",
      entityId: "ent-003",
      type: "entity_created",
      timestamp: new Date("2025-01-09T08:00:00"),
      userId: "user-mobile-003",
      userName: "Field Worker C",
      deviceId: "device-android-002",
      data: { observation_id: "WO-4521", species: "Red-tailed Hawk", count: 2 },
      metadata: { version: 1 },
    },
  ],
}

export const mockConflicts: ConflictDetail[] = [
  {
    id: "conflict-001",
    entityId: "ent-002",
    formAppId: "fa-001",
    formAppName: "Field Survey 2025",
    formName: "Water Quality Test",
    detectedAt: new Date("2025-01-09T11:50:00"),
    resolvedAt: new Date("2025-01-09T11:50:05"),
    status: "resolved",
    conflictType: "concurrent_update",
    localVersion: 2,
    remoteVersion: 1,
    conflictingFields: [
      {
        field: "turbidity",
        localValue: "low",
        remoteValue: "medium",
        resolvedValue: "low",
      },
    ],
    resolutionStrategy: "latest_wins",
    resolvedBy: "System",
  },
  {
    id: "conflict-002",
    entityId: "ent-004",
    formAppId: "fa-001",
    formAppName: "Field Survey 2025",
    formName: "Site Assessment",
    detectedAt: new Date("2025-01-08T16:30:00"),
    resolvedAt: new Date("2025-01-08T16:45:00"),
    status: "resolved",
    conflictType: "concurrent_update",
    localVersion: 3,
    remoteVersion: 2,
    conflictingFields: [
      {
        field: "status",
        localValue: "in_progress",
        remoteValue: "completed",
        resolvedValue: "in_progress",
      },
      {
        field: "notes",
        localValue: "Additional testing required",
        remoteValue: "All tests completed",
        resolvedValue: "Additional testing required",
      },
    ],
    resolutionStrategy: "manual",
    resolvedBy: "Sarah Johnson",
  },
  {
    id: "conflict-003",
    entityId: "ent-006",
    formAppId: "fa-002",
    formAppName: "Customer Feedback",
    formName: "Product Satisfaction",
    detectedAt: new Date("2025-01-09T10:15:00"),
    resolvedAt: null,
    status: "pending",
    conflictType: "network_partition",
    localVersion: 2,
    remoteVersion: 2,
    conflictingFields: [
      {
        field: "rating",
        localValue: 4,
        remoteValue: 5,
      },
      {
        field: "comments",
        localValue: "Good product, minor issues",
        remoteValue: "Excellent product",
      },
    ],
    resolutionStrategy: undefined,
    resolvedBy: undefined,
  },
  {
    id: "conflict-004",
    entityId: "ent-007",
    formAppId: "fa-005",
    formAppName: "Health & Safety Compliance",
    formName: "Incident Report",
    detectedAt: new Date("2025-01-09T14:00:00"),
    resolvedAt: null,
    status: "pending",
    conflictType: "version_mismatch",
    localVersion: 1,
    remoteVersion: 3,
    conflictingFields: [
      {
        field: "severity",
        localValue: "low",
        remoteValue: "high",
      },
    ],
    resolutionStrategy: undefined,
    resolvedBy: undefined,
  },
]

export function getFormAppById(id: string): FormApp | undefined {
  return mockFormApps.find((app) => app.id === id)
}

export function getEntitiesByFormAppId(formAppId: string): Entity[] {
  return mockEntities[formAppId] || []
}

export function getEventsByEntityId(entityId: string): Event[] {
  return mockEvents[entityId] || []
}

export function getFormDefinitionsByFormAppId(formAppId: string): FormDefinition[] {
  return mockFormDefinitions[formAppId] || []
}

export function getAllConflicts(): ConflictDetail[] {
  return mockConflicts
}

export function getConflictsByStatus(status: "pending" | "resolved" | "failed"): ConflictDetail[] {
  return mockConflicts.filter((conflict) => conflict.status === status)
}
